FROM python:3.12-slim-trixie

ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG NO_PROXY

ENV HTTP_PROXY=$HTTP_PROXY
ENV HTTPS_PROXY=$HTTPS_PROXY
ENV NO_PROXY=$NO_PROXY

COPY --from=ghcr.io/astral-sh/uv:0.10.9 /uv /uvx /bin/

RUN uv venv --system-site-packages /venv
ENV VIRTUAL_ENV=/venv
ENV PATH="/venv/bin:$PATH"

# Prevent migrator from syncing when using `uv run`
ENV UV_NO_SYNC=1

WORKDIR /code

COPY pyproject.toml uv.lock ./
COPY components ./components

WORKDIR /code/components/db
RUN uv sync --no-dev --active --no-install-project --extra migrations && uv pip install -e .

COPY components/db/containers/migrator/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
