services:
  devcontainer:
    extends:
      file: ../docker-compose.devcontainer.yml
      service: devcontainer
    volumes:
      - /mnt/wslg/.X11-unix:/tmp/.X11-unix
      - type: bind
        source: ../..
        target: /workspace
        read_only: false
    environment:
      DISPLAY: ${DISPLAY}
      QT_QPA_PLATFORM: xcb

volumes:
  prek-cache:
  venv-workspace:
  uv-cache:
