services:
  devcontainer:
    extends:
      file: ../docker-compose.devcontainer.yml
      service: devcontainer
    volumes:
      - /mnt/wslg:/mnt/wslg
      - type: bind
        source: ../..
        target: /workspace
        read_only: false
    environment:
      WAYLAND_DISPLAY: wayland-0
      XDG_RUNTIME_DIR: /mnt/wslg/runtime-dir
      QT_QPA_PLATFORM: wayland

volumes:
  prek-cache:
  venv-workspace:
  uv-cache:
