# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [ pre-commit ]
default_install_hook_types: [ pre-commit, commit-msg ]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        stages: [ "pre-commit" ]
      - id: end-of-file-fixer
        stages: [ "pre-commit" ]
      - id: mixed-line-ending
        name: LF for all files
        args: [ --fix=lf ]
      - id: check-json
        exclude: '.devcontainer/devcontainer.json'
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-xml
      - id: debug-statements

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.48.0
    hooks:
      - id: markdownlint
        files: \.md$
        exclude: CHANGELOG\.md$
        args: [ "--fix" ]
  # TOML formatter
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
  # Insert copyright header
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.6
    hooks:
      - id: insert-license
        name: insert MIT copyright header
        files: \.py$
        # exclude QGIS plugin files, since it is licensed under GPLv3
        exclude: ^(components/qgis_plugin/.*\.py)$
        args:
          - --license-filepath
          - .mit-copyright.txt
          - --use-current-year
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.5
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix, --extend-fixable=F401 ]
      - id: ruff-format
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-pyproject==1.2.4
          - flake8-spellcheck==0.28.0
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        exclude: ^(components/db/.*\.py)$ # db has its own mypy
        args: [ --explicit-package-bases ] # for monorepo components
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.38.0
    hooks:
      - id: yamllint
        args: [ --strict, -c=.yamllint ]
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
  - repo: https://github.com/ansible/ansible-lint
    rev: v26.3.0
    hooks:
      - id: ansible-lint
        always_run: false # to only run when any file matched
        files: ^infra/ansible/.*\.(yaml|yml)$
        exclude: ^infra/ansible/files/.*$
        args: [ "infra/ansible" ]
        additional_dependencies:
          - ansible==13.4.0
  - repo: https://github.com/nlsfi/qgis-plugin-dev-tools
    rev: v0.12.0
    hooks:
      - id: normalize-xml


  # commit-msg hooks
  # Commit messages should follow [Conventional Commits notation](https://www.conventionalcommits.org/en/v1.0.0/#summary).
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        stages: [ commit-msg ]
