# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [pre-commit]
default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        stages: ["pre-commit"]
      - id: end-of-file-fixer
        stages: ["pre-commit"]
      - id: mixed-line-ending
        name: LF for all files
        args: [--fix=lf]
      - id: check-json
        exclude: '.devcontainer/devcontainer.json'
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.48.0
    hooks:
      - id: markdownlint
        args: ["--fix"]
  # TOML formatter
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format

  # commit-msg hooks
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        stages: [commit-msg]
