services:
  db:
    build:
      context: infra/containers/postgis
      dockerfile: Containerfile
    image: localhost/pinta-db:latest
    healthcheck:
      test: pg_isready -U postgres || exit 1
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 30s
    ports:
      - target: 5432
        published: "${COMPOSE_DB_PORT:-5400}"
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: db-data
        target: /pgdata


  ansible:
    profiles:
      - ansible
    depends_on:
      - db
    build:
      context: infra/containers/ansible
      dockerfile: Containerfile
    image: localhost/pinta-ansible:latest
    environment:
      ANSIBLE_CONFIG: /ansible/ansible.cfg
    working_dir: /ansible
    command:
      - ansible-playbook
      - full.yml
      - -i
      - inventories/local
    volumes:
      - type: bind
        source: ./infra/ansible
        target: /ansible
        read_only: true
      - type: bind
        source: .
        target: /repository
        read_only: true

volumes:
  db-data:
