all:
  hosts:
    server:
      ansible_connection: ansible.builtin.ssh
      ansible_python_interpreter: /usr/bin/python3.12
      ansible_host: server
      ansible_user: deployer
      ansible_password: deployer
      ansible_host_key_checking: false
      ansible_ssh_pipelining: true
      install_dependencies: false  # provided by dockerfile installs

  vars:
    db_admin_user: admin
    db_admin_password: admin

    db_host: db
    db_port: 5432

    db_owner_role_name: pinta_owner
    db_writer_role_name: pinta_writer
    db_reader_role_name: pinta_reader

    application_dbs:
      - name: pinta

    application_db_roles:
      - name: "{{ db_reader_role_name }}"
      - name: "{{ db_writer_role_name }}"
        roles:
          - "{{ db_reader_role_name }}"

    application_db_users:
      - name: qgis_editor
        password: qgis
        roles:
          - "{{ db_writer_role_name }}"
      - name: qgis_viewer
        password: qgis
        roles:
          - "{{ db_reader_role_name }}"

    local_repository_path: /repository
    dest_repository_path: /opt/app
    db_component_dest_path: "{{ dest_repository_path }}/database"
    db_version: head # latest
