# Copyright (c) 2026 National Land Survey of Finland
# (https://www.maanmittauslaitos.fi/en).
# This file is part of the Pinta.
# Licensed under the MIT License; see the repository LICENSE file.

"""add production area and point cloud tables

Revision ID: 001
Revises:
Create Date: 2026-03-12 17:29:46.043733

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "production_area",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "geom",
            Geometry(
                geometry_type="MULTIPOLYGON",
                srid=3067,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_area")),
        schema="management",
    )
    op.create_geospatial_index(
        "idx_production_area_geom",
        "production_area",
        ["geom"],
        unique=False,
        schema="management",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_table(
        "point_cloud_tile",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "geom",
            Geometry(
                geometry_type="POLYGON",
                srid=3067,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("production_area_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["production_area_id"],
            ["management.production_area.id"],
            name=op.f("fk_point_cloud_tile_production_area_id_production_area"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_point_cloud_tile")),
        schema="management",
    )
    op.create_geospatial_index(
        "idx_point_cloud_tile_geom",
        "point_cloud_tile",
        ["geom"],
        unique=False,
        schema="management",
        postgresql_using="gist",
        postgresql_ops={},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(
        "idx_point_cloud_tile_geom",
        table_name="point_cloud_tile",
        schema="management",
        postgresql_using="gist",
        column_name="geom",
    )
    op.drop_geospatial_table("point_cloud_tile", schema="management")
    op.drop_geospatial_index(
        "idx_production_area_geom",
        table_name="production_area",
        schema="management",
        postgresql_using="gist",
        column_name="geom",
    )
    op.drop_geospatial_table("production_area", schema="management")
    # ### end Alembic commands ###
