# Copyright (c) 2026 National Land Survey of Finland
# (https://www.maanmittauslaitos.fi/en).
# This file is part of the Pinta.
# Licensed under the MIT License; see the repository LICENSE file.

"""temp migration

Revision ID: 001
Revises:
Create Date: 2026-03-16 11:10:27.081847

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op
from geoalchemy2 import Geometry

from pinta_db.env import SRID

# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "temporary_model",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "geom",
            Geometry(
                geometry_type="POINT",
                srid=SRID,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_temporary_model")),
        schema="temp_schema",
    )
    op.create_geospatial_index(
        "idx_temporary_model_geom",
        "temporary_model",
        ["geom"],
        unique=False,
        schema="temp_schema",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_table(
        "temporary_model_with_foreign_key",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "geom",
            Geometry(
                geometry_type="LINESTRING",
                srid=SRID,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("temp_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["temp_id"],
            ["temp_schema.temporary_model.id"],
            name=op.f("fk_temporary_model_with_foreign_key_temp_id_temporary_model"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_temporary_model_with_foreign_key")),
        schema="temp_schema",
    )
    op.create_geospatial_index(
        "idx_temporary_model_with_foreign_key_geom",
        "temporary_model_with_foreign_key",
        ["geom"],
        unique=False,
        schema="temp_schema",
        postgresql_using="gist",
        postgresql_ops={},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(
        "idx_temporary_model_with_foreign_key_geom",
        table_name="temporary_model_with_foreign_key",
        schema="temp_schema",
        postgresql_using="gist",
        column_name="geom",
    )
    op.drop_geospatial_table("temporary_model_with_foreign_key", schema="temp_schema")
    op.drop_geospatial_index(
        "idx_temporary_model_geom",
        table_name="temporary_model",
        schema="temp_schema",
        postgresql_using="gist",
        column_name="geom",
    )
    op.drop_geospatial_table("temporary_model", schema="temp_schema")
    # ### end Alembic commands ###
