[project]
name = "pinta-e2e"
version = "0.0.0"
description = "End to end tests for elevation production system"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "requests",
]
[project.optional-dependencies]
# QGIS requirements are marked here to allow starting QGIS from venv without conflicting dependencies

[project.urls]
Homepage = "https://github.com/nlsfi/pinta"
Repository = "https://github.com/nlsfi/pinta"

[build-system]
requires = ["uv_build>=0.10.9,<0.12.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "pinta_e2e_utils"
include = ["py.typed"]

[tool.uv]
default-groups = ["dev", "lint", "qgis", "airflow"]

[tool.uv.sources]
pinta-qgis-plugin = { workspace = true }
pinta-lib = { workspace = true }
pinta-dags = { workspace = true }
pinta-backend = { workspace = true }

[dependency-groups]
dev = [
  "pinta-lib",
  "pinta-backend",
  "pytest>=9.0.2",
  "pytest-xdist>=3.8.0",
  "psycopg",
  "pytest-mock>=3.0.0",
  "pytest-timeout",
]
lint = [
  "prek",
  "mypy",
  "ruff",
]
# List all dev depencies that require Qt and/or QGIS here
qgis = [
  "pinta-qgis-plugin",
  "pytest-qgis",
  "pytest-qt",
]
# List all dev depencies that require Airflow here
airflow = [
  "pinta-dags[airflow]",
]

[tool.pytest.ini_options]
testpaths = [
  "test_e2e",
]
addopts = "-n auto --dist loadgroup --maxprocesses=4 --import-mode=importlib"
timeout = 180
timeout_method = "thread"
