repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: fc0f09a29bb495f4a91f00266155d6282d52485d  # frozen: v1.20.2
    hooks:
      - id: mypy
        args: [ --explicit-package-bases ] # for monorepo components
        additional_dependencies:
          - sqlmodel
