- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ install_component_dest_path }}"
    state: directory
    mode: u=rwx,g=rx,o=rx
  become: true

- name: Upload application component {{ install_component_name }}
  ansible.posix.synchronize:
    src: "{{ install_component_path }}"
    dest: "{{ install_component_dest_path }}"
    delete: true
  become: true

# TODO: remove this when lock file problem is solved
- name: Remove tool.uv.sources section and pinta-lib dependency using sed
  ansible.builtin.shell: |
    # Remove the [tool.uv.sources] section completely
    sed -i '/^\[tool\.uv\.sources\]/,/^\[/ { /^\[/!d; }' pyproject.toml
    # Remove 'pinta-lib' from project.dependencies
    sed -i 's/\(["'\'']\?pinta-lib["'\'']\?,\?\s*\)//g' pyproject.toml
  args:
    executable: /bin/bash
    chdir: "{{ install_component_dest_path }}/{{ install_component_name }}"
  changed_when: true

# TODO: should lock file should be generated for each component?
- name: Generate application lock file
  ansible.builtin.command: "{{ install_component_uv_path }} lock"
  environment:
    UV_DEFAULT_INDEX: "{{ install_component_pip_index_url }}"
  args:
    chdir: "{{ install_component_dest_path }}/{{ install_component_name }}"
  become: true
  changed_when: true

- name: Install application component {{ install_component_name }}
  ansible.builtin.command: "{{ install_component_uv_path }} sync --no-cache {{ install_component_dev_deps | ternary('--group=dev', '') }}"
  environment:
    UV_DEFAULT_INDEX: "{{ install_component_pip_index_url }}"
  args:
    chdir: "{{ install_component_dest_path }}/{{ install_component_name }}"
  become: true
  changed_when: true
