repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.6
    hooks:
      - id: insert-license  # Insert a short license disclaimer as a header comment in source files
        files: \.py$
        args:
          - --license-filepath
          - copyright-header.txt
          - --use-current-year
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-pyproject==1.2.4
          - flake8-qgis==1.0.0

  - repo: https://github.com/nlsfi/qgis-plugin-dev-tools
    rev: update-translations-hook
    hooks:
      - id: update-translations
