ARG PROCESSING_BUILD_DEPS_IMAGE=ghcr.io/nlsfi/pinta/processing-build-deps:latest

FROM ${PROCESSING_BUILD_DEPS_IMAGE} AS processing-build-deps

FROM redhat/ubi10:10.1

# Proxy args
ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG NO_PROXY

ENV HTTP_PROXY=$HTTP_PROXY
ENV HTTPS_PROXY=$HTTPS_PROXY
ENV NO_PROXY=$NO_PROXY

ARG ENABLE_REPOS="*"
ARG DISABLE_REPOS=""
ARG ADDITIONAL_REPO_CONTENTS=""

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# hadolint ignore=DL3041, SC3009
RUN if [ -n "$ADDITIONAL_REPO_CONTENTS" ]; then \
      echo "$ADDITIONAL_REPO_CONTENTS" > /etc/yum.repos.d/extra.repo; \
  fi && \
  dnf update \
    -y \
    --disablerepo="${DISABLE_REPOS}" \
    --enablerepo="${ENABLE_REPOS}" \
  && dnf \
      --disableplugin=subscription-manager \
      --disablerepo="${DISABLE_REPOS}" \
      --enablerepo="${ENABLE_REPOS}" \
      --allowerasing \
      install -y python3.12 python3.12-pip \
      # LASTools dependencies
      libpng libjpeg-turbo \
      # proj dependencies
      sqlite sqlite-devel curl libcurl libcurl-devel \
  && dnf --disableplugin=subscription-manager clean all \
  && ln -s /usr/bin/python3.12 /usr/bin/python \
  && mv /usr/bin/python3{,9} \
  && ln -s /usr/bin/python3.12 /usr/bin/python3

COPY --from=processing-build-deps /usr/local/lib64/ /usr/local/lib64/
COPY --from=processing-build-deps /usr/local/lib/ /usr/local/lib/
COPY --from=processing-build-deps /usr/local/include/nlohmann/json.hpp /usr/local/include/nlohmann/

# Update paths to include the newly added libraries and headers
RUN echo "/usr/local/lib64" > /etc/ld.so.conf.d/proj.conf && \
  echo "/usr/local/lib" > /etc/ld.so.conf.d/local.conf && ldconfig

# Verify that all LASTools dependencies are installed
# hadolint ignore=DL3003
RUN mkdir -p /lastools && cd /lastools && curl -fsSL https://downloads.rapidlasso.de/LAStools.tar.gz -o lastools.tar.gz \
  && tar -xzf lastools.tar.gz \
  && cd bin \
  && ldd blast2dem64 | grep "not found" && echo "Missing dependencies for LASTools!" && exit 1 || echo "All LASTools dependencies are installed." \
  && cd .. \
  && rm -rf lastools.tar.gz LAStools

# hadolint ignore=DL3013
RUN python -m pip install --upgrade pip --no-cache-dir \
  && pip install uv --no-cache-dir

WORKDIR /code

COPY components/processing/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY pyproject.toml uv.lock ./
COPY components ./components

RUN uv venv /venv
ENV VIRTUAL_ENV=/venv
ENV PATH="/venv/bin:$PATH"
WORKDIR /code/components/processing
RUN uv sync --no-dev --active --no-install-project && uv pip install -e .

ENTRYPOINT ["/entrypoint.sh"]
