# This Containerfile is part of multi-stage build for the processing container.
# The image includes only the dependencies which are built from source.

FROM redhat/ubi10:10.1

# Version args are used for default download URLs.
ARG LIBTIFF_VERSION=4.7.1
ARG LIBGEOTIFF_VERSION=1.7.4
ARG PROJ_VERSION=9.7.1
ARG NLOHMANN_JSON_VERSION=3.7.3

# Source path args are optional. Set them to paths under
# the build-dependecies/ directory in build context
# to use copied source artifacts instead, for example:
#   --build-arg LIBTIFF_SOURCE_PATH=tiff-4.7.1.tar.gz
# where tiff-4.7.1.tar.gz is located in build-dependecies/
ARG LIBTIFF_SOURCE_PATH=
ARG LIBGEOTIFF_SOURCE_PATH=
ARG PROJ_SOURCE_PATH=
ARG NLOHMANN_JSON_SOURCE_PATH=

ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG NO_PROXY

ENV HTTP_PROXY=$HTTP_PROXY
ENV HTTPS_PROXY=$HTTPS_PROXY
ENV NO_PROXY=$NO_PROXY

ARG ENABLE_REPOS="*"
ARG DISABLE_REPOS=""
ARG ADDITIONAL_REPO_CONTENTS=""

WORKDIR /tmp/build

COPY build-dependecies/ .

# hadolint ignore=DL3041, SC3009
RUN if [ -n "$ADDITIONAL_REPO_CONTENTS" ]; then \
      echo "$ADDITIONAL_REPO_CONTENTS" > /etc/yum.repos.d/extra.repo; \
  fi && \
  dnf update \
    -y \
    --disablerepo="${DISABLE_REPOS}" \
    --enablerepo="${ENABLE_REPOS}" \
  && dnf install \
      -y \
      --disableplugin=subscription-manager \
      --disablerepo="${DISABLE_REPOS}" \
      --enablerepo="${ENABLE_REPOS}" \
      --allowerasing \
      # libtiff build dependencies
      gcc make cmake autoconf automake libtool g++ \
      # libgeotiff build dependencies
      unzip zip diffutils \
      # proj build dependencies
      sqlite sqlite-devel curl libcurl libcurl-devel \
  && dnf --disableplugin=subscription-manager clean all

# Build and install libtiff
# hadolint ignore=DL3003
RUN if [ -n "${LIBTIFF_SOURCE_PATH}" ]; then \
      cp "${LIBTIFF_SOURCE_PATH}" libtiff.tar.gz; \
    else \
      curl -fsSL https://download.osgeo.org/libtiff/tiff-${LIBTIFF_VERSION}.tar.gz -o libtiff.tar.gz; \
    fi \
  && tar -xzf libtiff.tar.gz \
  && cd tiff-${LIBTIFF_VERSION} \
  && ./configure \
  && make \
  && make install \
  && cd .. \
  && rm -rf libtiff.tar.gz tiff-${LIBTIFF_VERSION}

# Install nlohmann/json
RUN mkdir -p /usr/local/include/nlohmann \
  && if [ -n "${NLOHMANN_JSON_SOURCE_PATH}" ]; then \
      cp "${NLOHMANN_JSON_SOURCE_PATH}" /usr/local/include/nlohmann/json.hpp; \
    else \
      curl -fsSL https://github.com/nlohmann/json/releases/download/v${NLOHMANN_JSON_VERSION}/json.hpp -o /usr/local/include/nlohmann/json.hpp; \
    fi

# Install proj
# hadolint ignore=DL3003
RUN if [ -n "${PROJ_SOURCE_PATH}" ]; then \
      cp "${PROJ_SOURCE_PATH}" proj.tar.gz; \
    else \
      curl -fsSL https://download.osgeo.org/proj/proj-${PROJ_VERSION}.tar.gz -o proj.tar.gz; \
    fi \
  && tar -xzf proj.tar.gz \
  && cd proj-${PROJ_VERSION} \
  && mkdir build && cd build \
  && cmake -DBUILD_TESTING=OFF .. \
  && cmake --build . \
  && cmake --build . --target install \
  && cd ../.. \
  && rm -rf proj.tar.gz proj-${PROJ_VERSION}

# Add proj for libgeotiff build
RUN echo "/usr/local/lib64" > /etc/ld.so.conf.d/proj.conf && \
  echo "/usr/local/lib" > /etc/ld.so.conf.d/local.conf && ldconfig

# Install libgeotiff
# hadolint ignore=DL3003
RUN if [ -n "${LIBGEOTIFF_SOURCE_PATH}" ]; then \
      cp "${LIBGEOTIFF_SOURCE_PATH}" libgeotiff.zip; \
    else \
      curl -fsSL https://github.com/OSGeo/libgeotiff/releases/download/${LIBGEOTIFF_VERSION}/libgeotiff-${LIBGEOTIFF_VERSION}.zip -o libgeotiff.zip; \
    fi \
  && unzip libgeotiff.zip \
  && cd libgeotiff-${LIBGEOTIFF_VERSION} \
  && ./autogen.sh \
  && ./configure \
  && make dist \
  && tar xvzf libgeotiff*.tar.gz \
  && cd libgeotiff-${LIBGEOTIFF_VERSION} \
  && mkdir build_autoconf \
  && cd build_autoconf \
  && CFLAGS="-Wall -Wextra -Werror" ../configure \
  && make -j3 \
  && make check \
  && cd .. \
  && mkdir build_cmake \
  && cd build_cmake \
  && cmake -DCMAKE_C_FLAGS="-Wall -Wextra -Werror" .. \
  && make -j3 \
  && make install \
  && cd .. \
  && rm -rf libgeotiff.zip libgeotiff-${LIBGEOTIFF_VERSION}
