# This Containerfile is part of multi-stage build for the processing container.
# The image includes only the dependencies which are built from source.

FROM redhat/ubi10:10.1

ARG LIBTIFF_SOURCE_URL=https://download.osgeo.org/libtiff/tiff-4.7.1.tar.gz
ARG LIBGEOTIFF_SOURCE_URL=https://github.com/OSGeo/libgeotiff/releases/download/1.7.4/libgeotiff-1.7.4.zip
ARG PROJ_SOURCE_URL=https://download.osgeo.org/proj/proj-9.7.1.tar.gz
ARG NLOHMANN_JSON_SOURCE_URL=https://github.com/nlohmann/json/releases/download/v3.7.3/json.hpp

ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG NO_PROXY

ENV HTTP_PROXY=$HTTP_PROXY
ENV HTTPS_PROXY=$HTTPS_PROXY
ENV NO_PROXY=$NO_PROXY

ARG ENABLE_REPOS="*"
ARG DISABLE_REPOS=""
ARG ADDITIONAL_REPO_CONTENTS=""


# hadolint ignore=DL3041, SC3009
RUN if [ -n "$ADDITIONAL_REPO_CONTENTS" ]; then \
      echo "$ADDITIONAL_REPO_CONTENTS" > /etc/yum.repos.d/extra.repo; \
  fi && \
  dnf update \
    -y \
    --disablerepo="${DISABLE_REPOS}" \
    --enablerepo="${ENABLE_REPOS}" \
  && dnf install \
      -y \
      --disableplugin=subscription-manager \
      --disablerepo="${DISABLE_REPOS}" \
      --enablerepo="${ENABLE_REPOS}" \
      --allowerasing \
      # libtiff build dependencies
      gcc make cmake autoconf automake libtool g++ \
      # libgeotiff build dependencies
      unzip zip diffutils \
      # proj build dependencies
      sqlite sqlite-devel curl libcurl libcurl-devel \
  && dnf --disableplugin=subscription-manager clean all

# Build and install libtiff
# hadolint ignore=DL3003
RUN mkdir libtiff-src \
  && curl -fsSL "${LIBTIFF_SOURCE_URL}" -o libtiff.tar.gz \
  && tar -xzf libtiff.tar.gz -C libtiff-src --strip-components=1 \
  && cd libtiff-src \
  && ./configure \
  && make \
  && make install \
  && cd .. \
  && rm -rf libtiff.tar.gz libtiff-src

# Install nlohmann/json
RUN curl -fsSL "${NLOHMANN_JSON_SOURCE_URL}" -o json.hpp && \
  mkdir -p /usr/local/include/nlohmann && \
  mv json.hpp /usr/local/include/nlohmann/

# Install proj
# hadolint ignore=DL3003
RUN mkdir proj-src \
  && curl -fsSL "${PROJ_SOURCE_URL}" -o proj.tar.gz \
  && tar -xzf proj.tar.gz -C proj-src --strip-components=1 \
  && cd proj-src \
  && mkdir build && cd build \
  && cmake .. \
  && cmake --build . \
  && cmake --build . --target install \
  && cd ../.. \
  && rm -rf proj.tar.gz proj-src

# Add proj for libgeotiff build
RUN echo "/usr/local/lib64" > /etc/ld.so.conf.d/proj.conf && \
  echo "/usr/local/lib" > /etc/ld.so.conf.d/local.conf && ldconfig

# Install libgeotiff
# hadolint ignore=DL3003, DL4006
RUN curl -fsSL "${LIBGEOTIFF_SOURCE_URL}" -o libgeotiff.zip \
  && mkdir libgeotiff-src \
  && unzip -q libgeotiff.zip -d libgeotiff-src \
  && cd "$(find libgeotiff-src -mindepth 1 -maxdepth 1 -type d | head -n 1)" \
  && ./autogen.sh \
  && ./configure \
  && make dist \
  && LIBGEOTIFF_DIST_DIR="$(tar -tzf libgeotiff*.tar.gz | head -n 1 | cut -d/ -f1)" \
  && tar xvzf libgeotiff*.tar.gz \
  && cd "${LIBGEOTIFF_DIST_DIR}" \
  && mkdir build_autoconf \
  && cd build_autoconf \
  && CFLAGS="-Wall -Wextra -Werror" ../configure \
  && make -j3 \
  && make check \
  && cd .. \
  && mkdir build_cmake \
  && cd build_cmake \
  && cmake -DCMAKE_C_FLAGS="-Wall -Wextra -Werror" .. \
  && make -j3 \
  && make install \
  && cd .. \
  && rm -rf libgeotiff.zip libgeotiff-src
