FROM redhat/ubi9:9.7

# Proxy args
ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG NO_PROXY

ENV HTTP_PROXY=$HTTP_PROXY
ENV HTTPS_PROXY=$HTTPS_PROXY
ENV NO_PROXY=$NO_PROXY

ARG ENABLE_REPOS="*"
ARG DISABLE_REPOS=""
ARG ADDITIONAL_REPO_CONTENTS=""

# hadolint ignore=DL3041, SC3009
RUN if [ -n "$ADDITIONAL_REPO_CONTENTS" ]; then \
      echo "$ADDITIONAL_REPO_CONTENTS" > /etc/yum.repos.d/extra.repo; \
  fi && \
  dnf update \
    -y \
    --disablerepo="${DISABLE_REPOS}" \
    --enablerepo="${ENABLE_REPOS}" \
  && dnf \
      --disableplugin=subscription-manager \
      --disablerepo="${DISABLE_REPOS}" \
      --enablerepo="${ENABLE_REPOS}" \
      install -y -vv python3.12 python3.12-pip \
  && dnf --disableplugin=subscription-manager clean all \
  && ln -s /usr/bin/python3.12 /usr/bin/python \
  && mv /usr/bin/python3{,9} \
  && ln -s /usr/bin/python3.12 /usr/bin/python3

# hadolint ignore=DL3013
RUN python -m pip install --upgrade pip --no-cache-dir \
  && pip install uv --no-cache-dir

# Lastools dependecies from debian based image
# RUN apt-get update && apt-get install -y \
#     libjpeg62 libpng-dev libtiff-dev libjpeg-dev \
#     libz-dev libproj-dev liblzma-dev libjbig-dev \
#     libzstd-dev libgeotiff-dev libwebp-dev

WORKDIR /code

COPY components/processing/entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

COPY uv.lock ./
COPY components/processing/pyproject.toml ./pyproject.toml
RUN uv sync --no-dev --active --no-install-project
COPY components/processing/src ./src
RUN uv pip install -e .

ENTRYPOINT ["./entrypoint.sh"]
