# Copyright (c) 2026 National Land Survey of Finland
# (https://www.maanmittauslaitos.fi/en).
# This file is part of the Pinta.
# Licensed under the MIT License; see the repository LICENSE file.

"""Add job tables

Revision ID: 002
Revises: 001
Create Date: 2026-04-21 05:45:54.878578

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry, Raster

from pinta_common import Settings

# revision identifiers, used by Alembic.
revision: str = "002"
down_revision: str | Sequence[str] | None = "001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "dem",
        sa.Column("rid", sa.BigInteger(), autoincrement=True, primary_key=True),
        sa.Column(
            "rast",
            Raster(
                spatial_index=False, from_text="raster", name="raster", nullable=False
            ),
            nullable=False,
        ),
        schema="reference",
    )
    op.create_index(
        "idx_dem_rast",
        "dem",
        [sa.literal_column("ST_ConvexHull(rast)")],
        unique=False,
        schema="reference",
        postgresql_using="gist",
    )
    op.create_geospatial_table(
        "diff",
        sa.Column("rid", sa.BigInteger(), autoincrement=True, primary_key=True),
        sa.Column(
            "rast",
            Raster(
                spatial_index=False, from_text="raster", name="raster", nullable=False
            ),
            nullable=False,
        ),
        schema="reference",
    )
    op.create_index(
        "idx_diff_rast",
        "diff",
        [sa.literal_column("ST_ConvexHull(rast)")],
        unique=False,
        schema="reference",
        postgresql_using="gist",
    )
    op.create_geospatial_table(
        "diff_dior",
        sa.Column("rid", sa.BigInteger(), autoincrement=True, primary_key=True),
        sa.Column(
            "rast",
            Raster(
                spatial_index=False, from_text="raster", name="raster", nullable=False
            ),
            nullable=False,
        ),
        schema="reference",
    )
    op.create_index(
        "idx_diff_dior_rast",
        "diff_dior",
        [sa.literal_column("ST_ConvexHull(rast)")],
        unique=False,
        schema="reference",
        postgresql_using="gist",
    )
    op.create_geospatial_table(
        "diff_polygon",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("relevance_score", sa.Float(), nullable=True),
        sa.Column(
            "geom",
            Geometry(
                geometry_type="POLYGON",
                srid=Settings.DB_SRID,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="reference",
    )
    op.create_geospatial_index(
        "idx_diff_polygon_geom",
        "diff_polygon",
        ["geom"],
        unique=False,
        schema="reference",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_table(
        "diff_polygon_cluster",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("energy_sum", sa.Float(), nullable=True),
        sa.Column("energy_distribution", sa.Float(), nullable=True),
        sa.Column("cluster_area", sa.Float(), nullable=True),
        sa.Column(
            "geom",
            Geometry(
                geometry_type="POLYGON",
                srid=Settings.DB_SRID,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="reference",
    )
    op.create_geospatial_index(
        "idx_diff_polygon_cluster_geom",
        "diff_polygon_cluster",
        ["geom"],
        unique=False,
        schema="reference",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_table(
        "update_area",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "geom",
            Geometry(
                geometry_type="POLYGON",
                srid=Settings.DB_SRID,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="user_data",
    )
    op.create_geospatial_index(
        "idx_update_area_geom",
        "update_area",
        ["geom"],
        unique=False,
        schema="user_data",
        postgresql_using="gist",
        postgresql_ops={},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(
        "idx_update_area_geom",
        table_name="update_area",
        schema="user_data",
        postgresql_using="gist",
        column_name="geom",
    )
    op.drop_geospatial_table("update_area", schema="user_data")
    op.drop_geospatial_index(
        "idx_diff_polygon_cluster_geom",
        table_name="diff_polygon_cluster",
        schema="reference",
        postgresql_using="gist",
        column_name="geom",
    )
    op.drop_geospatial_table("diff_polygon_cluster", schema="reference")
    op.drop_geospatial_index(
        "idx_diff_polygon_geom",
        table_name="diff_polygon",
        schema="reference",
        postgresql_using="gist",
        column_name="geom",
    )
    op.drop_geospatial_table("diff_polygon", schema="reference")
    op.drop_geospatial_index(
        "idx_diff_dior_rast",
        table_name="diff_dior",
        schema="reference",
        postgresql_using="gist",
        column_name="rast",
    )
    op.drop_geospatial_table("diff_dior", schema="reference")
    op.drop_geospatial_index(
        "idx_diff_rast",
        table_name="diff",
        schema="reference",
        postgresql_using="gist",
        column_name="rast",
    )
    op.drop_geospatial_table("diff", schema="reference")
    op.drop_geospatial_index(
        "idx_dem_rast",
        table_name="dem",
        schema="reference",
        postgresql_using="gist",
        column_name="rast",
    )
    op.drop_geospatial_table("dem", schema="reference")
    # ### end Alembic commands ###
