# Copyright (c) 2026 National Land Survey of Finland
# (https://www.maanmittauslaitos.fi/en).
# This file is part of the Pinta.
# Licensed under the MIT License; see the repository LICENSE file.

"""Add dissolved_geom to update area table

Revision ID: 014
Revises: 013
Create Date: 2026-08-26 14:16:37.882214

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry

from pinta_common import Settings

# revision identifiers, used by Alembic.
revision: str = "014"
down_revision: str | Sequence[str] | None = "013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_geospatial_column(
        "update_area",
        sa.Column(
            "dissolved_geom",
            Geometry(
                geometry_type="POLYGON",
                srid=Settings.DB_SRID,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        schema="user_data",
    )
    op.create_geospatial_index(
        "idx_update_area_dissolved_geom",
        "update_area",
        ["dissolved_geom"],
        unique=False,
        schema="user_data",
        postgresql_using="gist",
        postgresql_ops={},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(
        "idx_update_area_dissolved_geom",
        table_name="update_area",
        schema="user_data",
        postgresql_using="gist",
        column_name="dissolved_geom",
    )
    op.drop_geospatial_column("update_area", "dissolved_geom", schema="user_data")
    # ### end Alembic commands ###
