# Copyright (c) 2026 National Land Survey of Finland
# (https://www.maanmittauslaitos.fi/en).
# This file is part of the Pinta.
# Licensed under the MIT License; see the repository LICENSE file.

"""Add update area restore table

Revision ID: 017
Revises: 016
Create Date: 2026-09-02 11:33:17.107573

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry

from pinta_common import Settings

# revision identifiers, used by Alembic.
revision: str = "017"
down_revision: str | Sequence[str] | None = "016"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "update_area_restore",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "geom",
            Geometry(
                geometry_type="POLYGON",
                srid=Settings.DB_SRID,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="user_data",
    )
    op.create_geospatial_index(
        "idx_update_area_restore_geom",
        "update_area_restore",
        ["geom"],
        unique=False,
        schema="user_data",
        postgresql_using="gist",
        postgresql_ops={},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(
        "idx_update_area_restore_geom",
        table_name="update_area_restore",
        schema="user_data",
        postgresql_using="gist",
        column_name="geom",
    )
    op.drop_geospatial_table("update_area_restore", schema="user_data")

    # ### end Alembic commands ###
