# Copyright (c) 2026 National Land Survey of Finland
# (https://www.maanmittauslaitos.fi/en).
# This file is part of the Pinta.
# Licensed under the MIT License; see the repository LICENSE file.

"""Add update area delete trigger

Revision ID: 018
Revises: 017
Create Date: 2026-09-02 11:37:08.309675

"""

from collections.abc import Sequence

from alembic import op
from alembic_utils.pg_function import PGFunction
from alembic_utils.pg_trigger import PGTrigger

# revision identifiers, used by Alembic.
revision: str = "018"
down_revision: str | Sequence[str] | None = "017"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_data_save_dissolved_geom_on_delete = PGFunction(
        schema="user_data",
        signature="save_dissolved_geom_on_delete()",
        definition="RETURNS trigger AS $$\nBEGIN\n    IF OLD.dissolved_geom IS NOT NULL THEN\n        INSERT INTO user_data.update_area_restore (id, geom)\n        VALUES (gen_random_uuid(), OLD.dissolved_geom);\n    END IF;\n    RETURN NULL;\nEND; $$ LANGUAGE 'plpgsql' SECURITY DEFINER",
    )
    op.create_entity(user_data_save_dissolved_geom_on_delete)

    user_data_update_area_save_dissolved_geom_on_delete_trigger = PGTrigger(
        schema="user_data",
        signature="save_dissolved_geom_on_delete_trigger",
        on_entity="user_data.update_area",
        is_constraint=False,
        definition="AFTER DELETE ON user_data.update_area\n    FOR EACH ROW EXECUTE FUNCTION\n    user_data.save_dissolved_geom_on_delete()",
    )
    op.create_entity(user_data_update_area_save_dissolved_geom_on_delete_trigger)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_data_update_area_save_dissolved_geom_on_delete_trigger = PGTrigger(
        schema="user_data",
        signature="save_dissolved_geom_on_delete_trigger",
        on_entity="user_data.update_area",
        is_constraint=False,
        definition="AFTER DELETE ON user_data.update_area\n    FOR EACH ROW EXECUTE FUNCTION\n    user_data.save_dissolved_geom_on_delete()",
    )
    op.drop_entity(user_data_update_area_save_dissolved_geom_on_delete_trigger)

    user_data_save_dissolved_geom_on_delete = PGFunction(
        schema="user_data",
        signature="save_dissolved_geom_on_delete()",
        definition="RETURNS trigger AS $$\nBEGIN\n    IF OLD.dissolved_geom IS NOT NULL THEN\n        INSERT INTO user_data.update_area_restore (id, geom)\n        VALUES (gen_random_uuid(), OLD.dissolved_geom);\n    END IF;\n    RETURN NULL;\nEND; $$ LANGUAGE 'plpgsql' SECURITY DEFINER",
    )
    op.drop_entity(user_data_save_dissolved_geom_on_delete)

    # ### end Alembic commands ###
