# Copyright (c) 2026 National Land Survey of Finland
# (https://www.maanmittauslaitos.fi/en).
# This file is part of the Pinta.
# Licensed under the MIT License; see the repository LICENSE file.

"""Add processing status enum

Revision ID: 005_add_processing_status
Revises: 004
Create Date: 2026-05-25 05:43:15.230067

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "005_add_processing_status"
down_revision: str | Sequence[str] | None = "004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


processing_status_enum = postgresql.ENUM(
    "not_started",
    "queued",
    "started",
    "completed",
    "failure",
    name="processing_status",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    processing_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "production_area",
        sa.Column(
            "processing_status",
            processing_status_enum,
            server_default="not_started",
            nullable=False,
        ),
        schema="management",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("production_area", "processing_status", schema="management")
    processing_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
