# Copyright (c) 2026 National Land Survey of Finland
# (https://www.maanmittauslaitos.fi/en).
# This file is part of the Pinta.
# Licensed under the MIT License; see the repository LICENSE file.

"""Add processing status timestamp function

Revision ID: 008
Revises: 007
Create Date: 2026-06-29 15:44:47.246385

"""

from collections.abc import Sequence

from alembic import op
from alembic_utils.pg_function import PGFunction

# revision identifiers, used by Alembic.
revision: str = "008"
down_revision: str | Sequence[str] | None = "007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    management_update_processing_timestamp = PGFunction(
        schema="management",
        signature="update_processing_timestamp()",
        definition="RETURNS trigger AS $$\nBEGIN\n    IF NEW.processing_status <> OLD.processing_status THEN\n        NEW.processing_status_last_updated = now();\n    END IF;\n    RETURN NEW;\nEND; $$ LANGUAGE 'plpgsql'",
    )
    op.create_entity(management_update_processing_timestamp)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    management_update_processing_timestamp = PGFunction(
        schema="management",
        signature="update_processing_timestamp()",
        definition="RETURNS trigger AS $$\nBEGIN\n    IF NEW.processing_status <> OLD.processing_status THEN\n        NEW.processing_status_last_updated = now();\n    END IF;\n    RETURN NEW;\nEND; $$ LANGUAGE 'plpgsql'",
    )
    op.drop_entity(management_update_processing_timestamp)

    # ### end Alembic commands ###
