# Copyright (c) 2026 National Land Survey of Finland
# (https://www.maanmittauslaitos.fi/en).
# This file is part of the Pinta.
# Licensed under the MIT License; see the repository LICENSE file.

"""Add processing status timestamp trigger

Revision ID: 009
Revises: 008
Create Date: 2026-06-29 15:47:57.446632

"""

from collections.abc import Sequence

from alembic import op
from alembic_utils.pg_trigger import PGTrigger

# revision identifiers, used by Alembic.
revision: str = "009"
down_revision: str | Sequence[str] | None = "008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    management_production_area_update_processing_timestamp_trigger = PGTrigger(
        schema="management",
        signature="update_processing_timestamp_trigger",
        on_entity="management.production_area",
        is_constraint=False,
        definition="BEFORE UPDATE ON management.production_area\n    FOR EACH ROW EXECUTE FUNCTION management.update_processing_timestamp()",
    )
    op.create_entity(management_production_area_update_processing_timestamp_trigger)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    management_production_area_update_processing_timestamp_trigger = PGTrigger(
        schema="management",
        signature="update_processing_timestamp_trigger",
        on_entity="management.production_area",
        is_constraint=False,
        definition="BEFORE UPDATE ON management.production_area\n    FOR EACH ROW EXECUTE FUNCTION management.update_processing_timestamp()",
    )
    op.drop_entity(management_production_area_update_processing_timestamp_trigger)

    # ### end Alembic commands ###
