FROM alpine:3.23.3

ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG NO_PROXY

# hadolint ignore=DL3018
RUN apk add --no-cache \
    sudo \
    openssh-client \
    sshpass \
    python3 \
    py3-pip \
    unzip \
    rsync \
    git \
    vim \
    tar \
    bash \
    shadow

# Upgrade pip and install Python dependencies
# hadolint ignore=DL3013
RUN python3 -m pip install --no-cache-dir --break-system-packages --upgrade pip \
 && pip install --no-cache-dir --break-system-packages \
    ansible==13.4.0 \
    jmespath==1.1.0 \
    docker==7.1.0 \
    dnspython==2.8.0

# Install Ansible collections
RUN ansible-galaxy collection install community.postgresql:3.10.2 \
 && ansible-galaxy collection install community.general:10.3.0 \
 && ansible-galaxy collection install ansible.posix:1.6.2

# Create deploy user with passwordless sudo
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN adduser -D deployer \
 && echo "deployer ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers \
 && echo "Defaults:deployer !requiretty" >> /etc/sudoers \
 && echo "deployer:deployer" | chpasswd

# ---- SERVER DEPENDENCIES ----

# runtime dependencies used by playbooks
# hadolint ignore=DL3018
RUN apk add --no-cache \
    unzip \
    rsync

# required python packages
# hadolint ignore=DL3059
RUN pip install --no-cache-dir --break-system-packages \
    psycopg2-binary==2.9.11 \
    uv==0.10.9

# ---- END SERVER DEPENDENCIES ----

ENV ANSIBLE_SSH_RETRIES=5

WORKDIR /ansible

CMD ["echo", "nothing to do by default"]
