name: Build Devcontainer Container

on:
  push:
    branches: [ main ]
    paths:
      - '.devcontainer/**'
      - '.github/workflows/build-devcontainer.yml'
      - '.github/workflows/build-container.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '.devcontainer/**'
      - '.github/workflows/build-devcontainer.yml'
      - '.github/workflows/build-container.yml'

jobs:
  build:
    uses: ./.github/workflows/build-container.yml
    with:
      containerfile: .devcontainer/Containerfile
      context: .devcontainer
      image-name: devcontainer
      registry-image: ghcr.io/nlsfi/pinta/devcontainer
      push: ${{ github.event_name == 'push' || github.event_name == 'release' }}
  notify-teams:
    needs: build
    if: ${{ always() && needs.build.result == 'failure' && github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/notify-teams.yml
    with:
      job_name: Build devcontainer
    secrets: inherit
