name: Database Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'components/db/**'
      - '.github/workflows/db.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'components/db/**'
      - '.github/workflows/db.yml'

jobs:
  unittests:
    uses: ./.github/workflows/unit-tests.yml
    with:
      component-path: components/db

  integration_tests:
    uses: ./.github/workflows/integration-tests.yml
    with:
      component-path: components/db
