name: QGIS Plugin Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'components/qgis_plugin/**'
      - '.github/workflows/qgis_plugin.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'components/qgis_plugin/**'
      - '.github/workflows/qgis_plugin.yml'

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    container:
      image: qgis/qgis:3.44.8-noble
    defaults:
      run:
        working-directory: components/qgis_plugin
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python dependencies
        shell: bash
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python3 -m pip install uv
          uv sync --all-packages --all-groups --active

      - name: Run tests
        run: |
          pytest -v
