name: QGIS Plugin Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'components/qgis_plugin/**'
      - '.github/workflows/qgis_plugin.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'components/qgis_plugin/**'
      - '.github/workflows/qgis_plugin.yml'

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    container:
      image: qgis/qgis:${{ matrix.qgis-image-tags }}
    strategy:
      matrix:
        qgis-image-tags: [ "3.44.8-noble", "4.0-questing" ]
      fail-fast: false
    env:
      QT_QPA_PLATFORM: offscreen
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57

      - name: Install venv
        run: |
          uv venv --system-site-packages

      - name: Run tests
        run: |
          uv sync --locked
          uv run pytest -v
        working-directory: components/qgis_plugin
