name: Release

on:
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Publish to test PyPI instead of PyPi and do not push or create tags.'
        required: true
        default: false
        type: boolean
      components:
        description: 'Components to release given as an array.'
        required: true
        default: '["db", "processing", "qgis_plugin", "dags"]'
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: pypi-release
    env:
      UV_PUBLISH_INDEX: ${{ inputs.test_mode && 'testpypi' || 'pypi' }}
    permissions:
      contents: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        component: ${{ fromJSON(inputs.components) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Release component ${{ matrix.component }}
        id: release
        uses: python-semantic-release/python-semantic-release@v10.5.3
        with:
          directory: components/${{ matrix.component }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          vcs_release: false # TODO: set to true if we want to have github releases
          push: ${{ !inputs.test_mode }}

      # Publsh to PyPI only if the release was made
      - name: Install uv
        if: steps.release.outputs.released == 'true'
        uses: astral-sh/setup-uv@v5
      - name: Install Python
        if: steps.release.outputs.released == 'true'
        run: uv python install 3.13
      - name: Publish package (DRY RUN)
        if: steps.release.outputs.released == 'true'
        working-directory: components/${{ matrix.component }}
        run: uv publish --dry-run dist/*
      - name: Publish package to PyPI
        if: steps.release.outputs.released == 'true'
        working-directory: components/${{ matrix.component }}
        run: uv publish dist/*
